language: java
services:
  - mysql
before_install:
- mysql -e 'drop database if exists address_schema;'
- mysql -e 'create database address_schema;'
- mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('admin');"
- mysql -e "SET PASSWORD FOR 'root'@'127.0.0.1' = PASSWORD('admin');"
deploy:
   edge: true
   provider: cloudfoundry
   username: neha.d.daga@gmail.com
   password: vdsi2015
   api: https://api.run.pivotal.io
   organization: AddressValidation
   space: staging
  
